#!/bin/sh

# Uncomment the following two lines for normal desktop:
# unset SESSION_MANAGER
# exec /etc/X11/xinit/xinitrc

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources

VNCSERVERS="1:renyongxiang 2:renyongxiang"
VNCSERVERARGS[1]="-geometry 1920x1080 -depth 24"

xsetroot -solid grey
vncconfig -iconic &
x-terminal-emulator -geometry 1920x1080+0+0 -depth 24 -ls -title "$VNCDESKTOP Desktop" &
chromium-browser -depth 24 -ls
x-window-manager &
